name: PHP Linting & Testing 

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.4', '8.5', '8.6']

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: none,curl,dom,json,mbstring,pcre,xmlreader,sockets,simplexml,tokenizer,xml,xmlwriter,ctype

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: composer-dependency-analyser
        run: composer -v dev-composer-dependency-analyser

      - name: parallel-lint
        run: composer -v dev-parallel-lint

      - name: phpcs
        run: composer -v dev-phpcs

      - name: phpstan
        run: composer -v dev-phpstan

      - name: PHPUnit (with assertions)
        run: composer -v dev-phpunit-assertions

      - name: PHPUnit (without assertions)
        run: composer -v dev-phpunit-noassertions
