name: Tests

on:
  push:
  pull_request:

jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install cspell
        run: npm install -g cspell

      - name: cspell
        run: make cspell

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.4', '8.5', '8.6']

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: curl,dom,json,mbstring,pcre

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: composer-dependency-analyser
        run: make composer-dependency-analyser

      - name: parallel-lint
        run: make parallel-lint

      - name: phpcs
        run: make phpcs

      - name: phpstan
        run: make phpstan

      - name: PHPUnit (with assertions)
        run: make phpunit-assertions

      - name: PHPUnit (without assertions)
        run: make phpunit-noassertions
